_-UTILITY_EXPENSES_12M_L12
SUNCUTILITY_EXPENSES) OVERGPARTITION BY PTY ID, AGRANT. ID ORDER BY tXn-year, txn-month ROWS BETWEEN 24 PRECEDING AND 12 PRECEDING) AS UTILITY. EXPENSES_12M_L2,
-GROSS_CASH_INFLOW_12M_LO
SUN(GROSS_CASH INFLOW) OVER(PARTITION BY PTY.ID, AGRMNI-ID ORDER BY txn_year, txn_month ROWS 12 PRECEDING) as GROSS_CASH_INFLOW 12M_LO,
- -GROSS_CASH_INFLOW_12M_L12
SUN(GROSS_CASH_INFLOW) OVER CPARTITION BY PTY. ID, AGRHUT.ID ORDER BY tX-YBar, txn-month ROWS BETWEEN 24 PRECEDING AND 12 PRECEDING) AS GROSS_CASH_INFLOW _12M_ L1
- - LOANS_CREDIT_12M_LO
SUN(LOANS_CREDIT) OVER (PARTITION BY PTY ID, AGRIT_ID ORDER BY txn-year, txn month ROWS 12 PRECEDING) as LOANS_CREDIT .124_LO,
-- LOANS_CREDIT_12M_L12
SUM(LOANS _CREDIT) OVER(PARTITION BY PTY_ID, AGRINT.ID ORDER BY txn_year, txn_month ROWS BETWEEN 24 PRECEDING AND 12 PRECEDING) AS LOANS _CREDIT_12M_L12,
--TAXES_CREDIT_CREDIT_12M_LO
SUM(TAXES_CREDIT_CREDIT) OVER(PARTITION BY PTY_ID, AGRNNT.ID ORDER BY txn_year, txn_month ROWS 12 PRECEDING) as TAXES_CREDIT_CREDIT 12M_LO,
--TAXES_CREDIT_CREDIT_12M_L12
SUNCTAXES_CREDIT_CREDIT) OVER(PARTITION BY PTY.ID, AGRMNT.ID ORDER BY txn-year, txn_month ROWS BETWEEN 24 PRECEDING AND 12 PRECEDING) AS TAXES_CREDIT_CREDIT_121
-DIRECTOR_PAYMENT_CREDIT_12M_LO
SUM (DIRECTOR_ PAYNENT_CREDIT) OVER(PARTITION BY PTY_ID, AGRMNT.ID ORDER BY txn_year, txn_month ROWS 12 PRECEDING) as DIRECTOR_PAYMENT_CREDIT_12M_LO,
- -DIRECTOR_PAYMENT_CREDIT_12M_L12
SUM(DIRECTOR_PAYMENT _CREDIT) OVER(PARTITION BY PTY_ID, AGRMNT_ID ORDER BY txn_year, t×n_month ROWS BETWEEN 24 PRECEDING AND 12 PRECEDING) AS DIRECTOR_PAYMENT_CI _-CASH_ WITHDRAWALS_ 12M_LO
SUM (CASH_WITHDRAWALS) OVER (PARTITION BY PTY_ID, AGRMNT_ID ORDER BY txn_year, txn_month ROWS 12 PRECEDING) as CASH_WITHDRAWALS_12M_LE,
- -CASH_WITHDRAWALS_12M_L12
SUM(CASH_WITHDRAWALS) OVER (PARTITION BY PTY_ID, AGRINT_ ID ORDER BY txn_year, tx_month ROWS BETWEEN 24 PRECEDING AND 12 PRECEDING) AS CASH_MITHDRAWALS_12M_L12,
- - INTRA_GROUP_IN_12M_LO
SUM (INTRA_ERDUP_IN) OVER (PARTITION BY PTY_ID, AGRMNT_ID ORDER BY txn_year, txn_month ROWS 12 PRECEDING) as INTRA_GROUP_IN_ 121_L0,
--INTRA_GROUP_IN_12M_L12
SUMCINI
GROUP_IND OVER (PARTITION BY PTY_ID, AGRMNT_ID ORDER BY txn_year, txn_month ROWS BETWEEN 24 PRECEDING AND 12 PRECEDING) AS INTRA_GROUP_IN_12M_L12,
- VAT_12H_L0
SUM(VAT) OVER(PARTITION BY PTY_ID, AGRANT_ID ORDER BY txn_year, txn_month ROWS 12 PRECEDING) as VAT_12M_LO,
--VAT_12M_112
SUM(VAT) OVER (PARTITION BY PTY_ID, AGRMNT ID ORDER BY txn_year, txn_month ROWS BETWEEN 24 PRECEDING AND 12 PRECEDING) AS VAT_ 12M_ L12,
--CASH_FLOW_GROSS_12M_LB
e
1
2
3
5
97
98
SUN(CASH_FLOW _GROSS) OVER (PARTITION BY PTY_ID, AGRANT_ID ORDER BY txn_year, t×n_month ROWS 12 PRECEDING) as CASH_FLOW_GROSS_12M_ L0.
-- DEBIT COUNT YEARLY NILe
SUM(DEBIT_COUNT) OVER (PARTITION BY PTY_ID, AGRMNT ID ORDER BY txn_year, txn_month ROWS 12 PRECEDING) as DEBIT_COUNT_ YEARLY_M LO.
--DEBIT_COUNT_YEARLY_N_L12
SUM(DEBIT _COUNT) OVER (PARTITION BY PTY_ID, AGRUNT.-ID ORDER BY txn_year, txn_month ROWS BETWEEN 24 PRECEDING AND 12 PRECEDING) AS DEBIT_COUNT_ YEARLY_N_L12,
- INVOICE_FINANCE_12M_LO
SUMCINVOICE_FINANCE) OVER(PARTITION BY PTY_I0, AGRANT ID ORDER BY txn-year, txn-month ROWS 12 PRECEDING) as INVOICE. FINANCE_12M_L0.
- - INTRA_GROUP_OUT_12M_LO
SUM (INTRA_ GROUP-OUT) OVER(PARTITION BY PTY_I0, AGRANT-10 ORDER BY txn-year, txn-month ROWS 12 PRECEDING) as INTRA_GROUP_ OUT_12M LO.
